services:
  surrealdb:
    container_name: escrow-surrealdb
    hostname: surrealdb
    image: surrealdb/surrealdb:v2.3.3
    command: ["start", "--bind", "0.0.0.0:8000", "--user", "root", "--pass", "root"]
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - surrealdb-data:/data

volumes:
  surrealdb-data:
